from enum import StrEnum


PROJECTS_PER_PAGE = 12
USERS_PER_PAGE = 12

PROJECT_NAME_MAX_LENGTH = 200
PROJECT_STATUS_MAX_LENGTH = 6

USER_NAME_MAX_LENGTH = 124
USER_SURNAME_MAX_LENGTH = 124
USER_PHONE_MAX_LENGTH = 12
USER_ABOUT_MAX_LENGTH = 256

AVATAR_SIZE = 256
AVATAR_FONT_SIZE = 120
AVATAR_TEXT_COLOR = '#111111'


class AvatarColor(StrEnum):
    LIGHT_BLUE = '#DCEBFF'
    LIGHT_GREEN = '#E7F8EA'
    LIGHT_YELLOW = '#FFF1D6'
    LIGHT_PURPLE = '#F3E8FF'
    LIGHT_PINK = '#FFE4E6'
    LIGHT_CYAN = '#E0F2FE'


AVATAR_BACKGROUND_COLORS = tuple(color.value for color in AvatarColor)
